insert into algorithm(text, situation_id)
values ('x R'' U R'' D2 R U'' R'' D2 R2', 1),
       ('y x'' R2 D2 R'' U'' R D2 R'' U R''', 1),
       ('x R2 D2 R U R'' D2 R U'' R', 2),
       ('y x'' R U'' R D2 R'' U R D2 R2', 2),
       ('y x'' R U'' R'' D R U R'' D'' R U R'' D R U'' R'' D''', 3),
       ('R2 U R'' U'' y R U R'' U'' R U R'' U'' R U R'' y'' R U'' R2', 3),
       ('z U2 R2 F R U R'' U'' R U R'' U'' R U R'' U'' F'' R2 U2', 3),
       ('R2 U R2 U D R2 U'' R2 U R2 U'' D'' R2 U R2 U2 R2', 3),
       ('y R'' U'' F'' R U R'' U'' R'' F R2 U'' R'' U'' R U R'' U R', 4),
       ('y2 R'' U2 R'' Dw'' R'' F'' R2 U'' R'' U R'' F R U'' F', 4),
       ('R'' U R U'' R2 F'' U'' F U R F R'' F'' R2', 4),
       ('M'' U2 L F'' R U2 Rw'' U Rw'' R2 U2 R2', 4),
       ('D'' R2 U R'' U R'' U'' R U'' R2 U'' D R'' U R', 5),
       ('R2 Uw R'' U R'' U'' R Uw'' R2 y'' R'' U R', 5),
       ('R2 U R'' U R'' U'' R U'' R2 D U'' R'' U R D''', 5),
       ('R'' U'' R U D'' R2 U R'' U R U'' R U'' R2 D', 6),
       ('R'' U'' R y R2 Uw R'' U R U'' R Uw'' R2', 6),
       ('y F'' U'' F R2 Uw R'' U R U'' R Uw'' R2', 6),
       ('y2 R2 F2 R U2 R U2 R'' F R U R'' U'' R'' F R2', 7),
       ('R2 Uw'' R U'' R U R'' Uw R2 y R U'' R''', 7),
       ('R2 U'' R U'' R U R'' U R2 D'' U R U'' R'' D', 7),
       ('R U R'' U'' D R2 U'' R U'' R'' U R'' U R2 D''', 8),
       ('R U R'' y'' R2 Uw'' R U'' R'' U R'' Uw R2', 8),
       ('Fw R Fw'' R2 Uw'' R U'' R'' U R'' Uw R2', 8),
       ('M2 U M2 U2 M2 U M2', 9),
       ('M2 U'' M2 U2 M2 U'' M2', 9),
       ('R2 U2 R U2 R2 U2 R2 U2 R U2 R2', 9),
       ('y2 R'' U2 R U R'' U2 L U'' R U L''', 10),
       ('y R'' U L'' U2 R U'' R'' U2 R L', 10),
       ('L'' U'' L F L'' U'' L U L F'' L2 U L', 10),
       ('y2 x R2 F R F'' R U2 Rw'' U Rw U2', 10),
       ('R U R'' F'' R U R'' U'' R'' F R2 U'' R''', 11),
       ('R U2 R'' U'' R U2 L'' U R'' U'' L', 11),
       ('L'' U R U'' L U2 R'' U R U2 R''', 11),
       ('R U R'' U R U R'' F'' R U R'' U'' R'' F R2 U'' R'' U2 R U'' R''', 12),
       ('L U'' R U2 L'' U R'' L U'' R U2 L'' U R''', 12),
       ('z U R'' D R2 U'' R D'' U R'' D R2 U'' R D''', 12),
       ('Rw'' D Rw U2 Rw'' D Rw U2 Rw'' D Rw U2 Rw'' D Rw U2 Rw'' D Rw', 12),
       ('R'' U R U'' R'' F'' U'' F R U R'' F R'' F'' R U'' R', 13),
       ('R'' U L'' U2 R U'' L R'' U L'' U2 R U'' L', 13),
       ('z D'' R U'' R2 D R'' U D'' R U'' R2 D R'' U', 13),
       ('Rw D Rw'' U2 Rw D Rw'' U2 Rw D Rw'' U2 Rw D Rw'' U2 Rw D Rw''', 13),
       ('y R U R'' F'' R U2 R'' U2 R'' F R U R U2 R''', 14),
       ('L U2 L'' U2 L F'' L'' U'' L U L F L2', 14),
       ('y R U'' R'' U'' R U R D R'' U'' R D'' R'' U2 R''', 14),
       ('R'' U2 R U2 R'' F R U R'' U'' R'' F'' R2', 15),
       ('R'' U2 R'' D'' R U'' R'' D R U R U'' R'' U'' R', 15),
       ('y R2 F R U R U'' R'' F'' R U2 R'' U2 R', 15),
       ('y'' R U2 R'' U2 R'' F R2 U'' R'' U'' R U R'' F'' R U R'' U R U2 R''', 15),
       ('R U R'' U'' R'' F R2 U'' R'' U'' R U R'' F''', 16),
       ('R U R'' U'' R'' F R2 U'' R'' U F'' L'' U L', 16),
       ('R2 Uw'' R2 Uw R2 y R2 Uw R2 Uw'' R2', 16),
       ('R2 Uw R2 Uw'' R2 y'' R2 Uw'' R2 Uw R2', 16),
       ('y2 R U'' R U R U R U'' R'' U'' R2', 17),
       ('R2 U'' R'' U'' R U R U R U'' R', 17),
       ('y2 M2 U M U2 M'' U M2', 17),
       ('M2 U M'' U2 M U M2', 17),
       ('y2 R2 U R U R'' U'' R'' U'' R'' U R''', 18),
       ('R'' U R'' U'' R'' U'' R'' U R U R2', 18),
       ('y2 M2 U'' M U2 M'' U'' M2', 18),
       ('M2 U'' M'' U2 M U'' M2', 18),
       ('R'' U R'' Dw'' R'' F'' R2 U'' R'' U R'' F R F', 19),
       ('z D'' R2 D R2 U R'' D'' R U'' R U R'' D R U''', 19),
       ('R'' U R'' U'' R D'' R'' D R'' U D'' R2 U'' R2 D R2', 19),
       ('F R U'' R'' U'' R U R'' F'' R U R'' U'' R'' F R F''', 20),
       ('F R'' F R2 U'' R'' U'' R U R'' F'' R U R'' U'' F''', 20),
       ('R2 U'' R2 U'' R2 U R'' F'' R U R2 U'' R'' F R', 20),
       ('R2 D'' R2 U R2 U'' R2 D R2 U'' R2 U R2 U R2', 20),
       ('M2 U M2 U M'' U2 M2 U2 M''', 21),
       ('y M2 U'' M2 U'' M'' U2 M2 U2 M''', 21),
       ('M'' U'' M2 U'' M2 U'' M'' U2 M2', 21),
       ('y R'' U'' R U'' R U R U'' R'' U R U R2 U'' R''', 21);

insert into algorithm(text, situation_id)
values ('R U2 R2 F R F'' U2 R'' F R F''', 22),
       ('R U B'' R B R2 U'' R'' F R F''', 22),
       ('y R U'' R2 D'' Rw U'' Rw'' D R2 U R''', 22),
       ('Rw U R'' U R'' Rw2 U'' R'' U R'' Rw2 U2 Rw''', 22),
       ('F R U R'' U'' S R U R'' U'' Fw''', 23),
       ('y Rw U Rw'' U2 R U2 R'' U2 Rw U'' Rw''', 23),
       ('R'' U2 r U'' r'' U2 r U r'' U2 R', 23),
       ('y'' Fw R U R'' U'' Fw'' U'' F R U R'' U'' F''', 24),
       ('Rw'' R2 U R'' U Rw U2 Rw'' U M''', 24),
       ('y F U R U'' R'' F'' U F R U R'' U'' F''', 24),
       ('Rw'' R U R'' F2 R U L'' U L M''', 24),
       ('y'' Fw R U R'' U'' Fw'' U F R U R'' U'' F''', 25),
       ('M U'' Rw U2 Rw'' U'' R U'' R2 Rw', 25),
       ('y F U R U'' R'' F'' U'' F R U R'' U'' F''', 25),
       ('Rw'' U2 R U R'' U Rw', 26),
       ('F R U R'' U'' F'' U'' F R U R'' U'' F''', 26),
       ('Rw U2 R'' U'' R U'' Rw''', 27),
       ('y2 R U R2 F R F2 U F', 27),
       ('Rw U R'' U R U2 Rw''', 28),
       ('L'' U2 L U2 L F'' L'' F', 28),
       ('F R'' F'' R U2 R U2 R''', 28),
       ('y2 Rw'' U'' R U'' R'' U2 Rw', 29),
       ('Lw'' U'' L U'' L'' U2 Lw', 29),
       ('R U2 R'' U2 R'' F R F''', 29),
       ('F'' L F L'' U2 L'' U2 L', 29),
       ('y R U R'' U'' R'' F R2 U R'' U'' F''', 30),
       ('Rw'' R2 U2 R'' U'' R U'' R'' U'' M''', 30),
       ('y'' L'' U'' L U'' L F'' L'' F L'' U2 L', 30),
       ('y2 R'' U'' R U'' R'' U R'' F R F'' U R', 30),
       ('R U R'' U R'' F R F'' R U2 R''', 31),
       ('y2 L'' U'' L U L F'' L2 U'' L U F', 31),
       ('y2 Rw U R'' U R U'' R'' U'' Rw'' R U R U'' R''', 31),
       ('Rw'' R2 U R'' U R U2 R'' U M''', 32),
       ('y2 Rw U R'' U R'' F R F'' R U2 Rw''', 32),
       ('F R U R'' U'' F'' U F R U R'' U'' F''', 33),
       ('y'' M'' R'' U'' R U'' R'' U2 R U'' M', 33),
       ('Rw U'' Rw'' U'' Rw U Rw'' F'' U F', 34),
       ('F U R U2 R'' U'' R U R'' F''', 34),
       ('F U R U'' R2 F'' R U R U'' R''', 34),
       ('R'' F R U R'' F'' R F U'' F''', 35),
       ('Rw'' U Rw U Rw'' U'' Rw y R U'' R''', 35),
       ('Rw'' U'' Rw R'' U'' R U Rw'' U Rw', 36),
       ('y2 R'' F'' R L'' U'' L U R'' F R', 36),
       ('Rw U Rw'' R U R'' U'' Rw U'' Rw''', 37),
       ('y2 R'' F R U R'' U'' F'' R U'' R'' U2 R', 37),
       ('R U R'' U R'' F R F'' U2 R'' F R F''', 38),
       ('y2 F R'' F'' R2 Rw'' U R U'' R'' U'' M''', 38),
       ('Fw R U R'' U'' Fw'' U'' R U R'' U'' R'' F R F''', 38),
       ('Rw U R'' U R U2 Rw2 U'' R U'' R'' U2 Rw', 39),
       ('y R U2 R2 F R F'' U2 M'' U R U'' Rw''', 39),
       ('y2 F R U R'' Dw R'' U2 R'' F R F''', 39),
       ('M U R U R'' U'' M'' R'' F R F''', 40),
       ('Rw'' U2 R U R'' U Rw2 U2 R'' U'' R U'' Rw''', 40),
       ('R'' U2 F R U R'' U'' F2 U2 F R', 40),
       ('M U R U R'' U'' M2 U R U'' Rw''', 41),
       ('Rw U R'' U'' M2 U R U'' R'' U'' M''', 41),
       ('M'' U M'' U M'' U M'' U'' M'' U M'' U M'' U M''', 41),
       ('y R U2 R'' U'' R U R'' U'' R U'' R''', 42),
       ('y F R U R'' U'' R U R'' U'' R U R'' U'' F''', 42),
       ('R U R'' U R U'' R'' U R U2 R''', 42),
       ('R'' U'' R U'' R'' U R U'' R'' U2 R', 42),
       ('R U2 R2 U'' R2 U'' R2 U2 R', 43),
       ('Fw R U R'' U'' Fw'' F R U R'' U'' F''', 43),
       ('R'' U2 R2 U R2 U R2 U2 R''', 43),
       ('R2 D R'' U2 R D'' R'' U2 R''', 44),
       ('y2 R2 D'' R U2 R'' D R U2 R', 44),
       ('y R U R'' U'' R U'' R'' U2 R U'' R'' U2 R U R''', 44),
       ('R U R'' U R U2 R2 U'' R U'' R'' U2 R', 44),
       ('Rw U R'' U'' Rw'' F R F''', 45),
       ('y'' x'' R U R'' D R U'' R'' D''', 45),
       ('y F'' Rw U R'' U'' Rw'' F R', 46),
       ('F R'' F'' Rw U R U'' Rw''', 46),
       ('R'' F R B'' R'' F'' R B', 46),
       ('y R U2 R'' U'' R U'' R''', 47),
       ('R'' U'' R U'' R'' U2 R', 47),
       ('y2 L'' U'' L U'' L'' U2 L', 47),
       ('R'' U L U'' R U L''', 47),
       ('R U R'' U R U2 R''', 48),
       ('y'' R'' U2 R U R'' U R', 48),
       ('y L'' U2 L U L'' U L', 48),
       ('y2 L U L'' U L U2 L''', 48),
       ('R U'' L'' U R'' U'' L', 48),
       ('Rw U R'' U'' M U R U'' R''', 49),
       ('y2 M'' U M U2 M'' U M', 49),
       ('y'' M'' U'' M U2 M'' U'' M', 49),
       ('M U R U R'' U'' R'' F R F'' M''', 50),
       ('y R U R'' U'' R U'' R'' F'' U'' F R U R''', 50),
       ('Rw2 D'' Rw U Rw'' D Rw2 U'' Rw'' U'' Rw', 50),
       ('y2 R'' F R F'' R U2 R'' U'' F'' U'' F', 50),
       ('y2 F U R U2 R'' U'' R U2 R'' U'' F''', 51),
       ('y'' Rw'' D'' Rw U'' Rw'' D Rw2 U'' Rw'' U Rw U Rw''', 51),
       ('y2 F R'' F R2 U'' R'' U'' R U R'' F2', 51),
       ('M U'' L'' U'' L U L F'' L'' F M''', 51),
       ('Fw R U R2 U'' R'' U R2 U'' R'' Fw''', 51),
       ('R'' U'' F U R U'' R'' F'' R', 52),
       ('y2 S'' L'' U'' L U L F'' L'' Fw', 52),
       ('y'' F R'' F'' R U R U R'' U'' R U'' R''', 52),
       ('y S R U R'' U'' Fw'' U'' F', 52),
       ('S R U R'' U'' R'' F R Fw''', 53),
       ('R U B'' U'' R'' U R B R''', 53),
       ('y2 L U F'' U'' L'' U L F L''', 53),
       ('y2 F U R U'' F'' Rw U R'' U'' Rw''', 53),
       ('R U R'' U'' R'' F R F''', 54),
       ('F R U'' R'' U R U R'' F''', 54),
       ('y2 L'' U'' L U L F'' L'' F', 54),
       ('y'' Rw'' U'' Rw'' D'' Rw U Rw'' D Rw2', 54),
       ('y2 R U R2 U'' R'' F R U R U'' F''', 55),
       ('F R U R'' U'' R'' F'' Rw U R U'' Rw''', 55),
       ('R U2 R2 F R F'' R U2 R''', 56),
       ('Fw R U R'' U'' Fw'' R U R'' U R U2 R''', 56),
       ('y'' R U2 R'' U'' R U'' R'' U2 F R U R'' U'' F''', 56),
       ('y2 L'' U'' L U'' L'' U L U L F'' L'' F', 57),
       ('R'' U'' R U'' R'' U R U Lw U'' R'' U', 57),
       ('y2 R U R'' F'' R U R'' U'' R'' F R U'' R'' F R F''', 57),
       ('R U R'' U'' F'' U2 F U R U R''', 57),
       ('F R U'' R'' U'' R U R'' F''', 58),
       ('F R'' F'' R U R U'' R''', 58),
       ('R'' F R F'' U'' F'' U F', 58),
       ('y2 Rw2 D'' Rw U'' Rw'' D Rw U Rw', 58),
       ('R U R'' U R U'' R'' U'' R'' F R F''', 59),
       ('R'' U2 Rw'' D'' Rw U2 Rw'' D R Rw', 59),
       ('Rw U R'' U R U'' R'' U'' Rw'' F R F''', 59),
       ('y L F'' L'' U'' L U F U'' L''', 60),
       ('y'' R U R'' F'' U'' F U R U2 R''', 60),
       ('y F R U R'' U'' F'' R'' U'' R U'' R'' U2 R', 60),
       ('y R'' F R U R'' U'' F'' U R', 61),
       ('y'' Fw R'' F'' R U R U'' R'' S''', 61),
       ('y'' F R U R'' U'' F'' R U R'' U R U2 R''', 61),
       ('R Rw D Rw'' U Rw D'' Rw'' U'' R''', 61),
       ('y2 R U R'' U R U2 R'' F R U R'' U'' F''', 62),
       ('Fw R U R'' U'' Fw'' U'' R U R'' U R U2 R''', 62),
       ('R U'' R'' U2 R U y R U'' R'' U'' F''', 62),
       ('y'' L F'' L'' F L F'' L'' F L'' U'' L U L'' U'' L', 62),
       ('R'' U'' R U'' R'' U2 R F R U R'' U'' F''', 63),
       ('y R'' F R F'' R'' F R F'' R U R'' U'' R U R''', 63),
       ('M U F R U R'' U'' F'' M''', 63),
       ('L'' U L U2 L'' U'' y'' L'' U L U F', 63),
       ('Fw'' L'' U'' L U Fw', 64),
       ('y2 F'' U'' L'' U L F', 64),
       ('y R'' U'' F'' U F R', 64),
       ('Fw R U R'' U'' Fw''', 65),
       ('y2 F U R U'' R'' F''', 65),
       ('y'' F R U'' R'' F'' L'' U L', 65),
       ('F R U R'' U'' F''', 66),
       ('y2 Fw U R U'' R'' Fw''', 66),
       ('y2 F'' L'' U'' L U F', 66),
       ('R'' U'' R'' F R F'' U R', 67),
       ('y F R U R'' y'' R'' U R U2 R''', 67),
       ('F'' L'' U'' L U L'' U'' L U F', 68),
       ('R'' U'' R'' F R F'' R'' F R F'' U R', 68),
       ('y'' F R'' F'' R U2 R U'' R'' U R U2 R''', 68),
       ('F R U R'' U'' R U R'' U'' F''', 69),
       ('y2 Fw U R U'' R'' U R U'' R'' Fw''', 69),
       ('R U2 R'' U'' R U R'' U2 R'' F R F''', 69),
       ('y2 Rw U'' Rw2 U Rw2 U Rw2 U'' Rw', 70),
       ('R B'' R2 F R2 B R2 F'' R', 70),
       ('Rw'' U Rw2 U'' Rw2 U'' Rw2 U Rw''', 71),
       ('y2 R'' F R2 B'' R2 F'' R2 B R''', 71),
       ('y'' R U2 R'' U'' R U'' R'' F R U R'' U'' F''', 71),
       ('Fw R U R'' U'' R U R'' U'' Fw''', 72),
       ('y2 F U R U'' R'' U R U'' R'' F''', 72),
       ('y'' R'' U'' R'' F R F'' R U'' R'' U2 R', 72),
       ('R U R'' U R Dw'' R U'' R'' F''', 73),
       ('R'' U'' R U'' R'' U F'' U F R', 73),
       ('y2 R'' F'' U'' F U'' R U R'' U R', 73),
       ('Rw'' U'' R U'' R'' U R U'' R'' U2 Rw', 74),
       ('y Rw'' U2 R U R'' U'' R U R'' U Rw', 74),
       ('y2 F R U R'' U'' F'' R U R'' U'' R'' F R F''', 74),
       ('Rw U R'' U R U'' R'' U R U2 Rw''', 75),
       ('y'' Rw U2 R'' U'' R U R'' U'' R U'' Rw''', 75),
       ('y'' Rw U Rw'' R U R'' U'' R U R'' U'' Rw U'' Rw''', 75),
       ('R U2 R2 U'' R U'' R'' U2 F R F''', 76),
       ('y R'' F R U R U'' R2 F'' R2 U'' R'' U R U R''', 76),
       ('Rw U2 R2 F R F'' U2 Rw'' F R F''', 76),
       ('y R'' F U R U'' R2 F'' R2 U R'' U'' R', 76),
       ('Rw U Rw'' U R U'' R'' U R U'' R'' Rw U'' Rw''', 77),
       ('F R U R'' U'' R F'' Rw U R'' U'' Rw''', 77),
       ('Rw'' U'' Rw U'' R'' U R U'' R'' U R Rw'' U Rw', 77),
       ('R U R'' U'' M'' U R U'' Rw''', 78),
       ('M'' U M'' U M'' U2 M U M U M', 78),
       ('M'' U M'' U M'' U M'' U2 M'' U M'' U M'' U M''', 78);
